"""add image metadata to analyses

Revision ID: 08cdec678abf
Revises: 1ff2147aeb17
Create Date: 2026-09-06 01:08:27.623378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08cdec678abf'
down_revision: Union[str, Sequence[str], None] = '1ff2147aeb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analyses', 'image_width',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analyses', 'image_height',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('analyses', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('analyses', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('analyses', 'image_height',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analyses', 'image_width',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('analyses', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
