"""add image metadata to analyses

Revision ID: 1ff2147aeb17
Revises: 6c7b226e5a17
Create Date: 2026-09-06 00:12:51.874672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ff2147aeb17'
down_revision: Union[str, Sequence[str], None] = '6c7b226e5a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('analyses', sa.Column('image_width', sa.Integer(), nullable=False))
    op.add_column('analyses', sa.Column('image_height', sa.Integer(), nullable=False))
    op.add_column('analyses', sa.Column('content_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'content_type')
    op.drop_column('analyses', 'image_height')
    op.drop_column('analyses', 'image_width')
    op.drop_column('analyses', 'file_size')
    # ### end Alembic commands ###
